---
language: python
python: "2.7"

env:
  - SITE=test.yml

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - git clone https://github.com/futurice/ansible-pip.git ../ansible-pip
  - git clone https://github.com/futurice/ansible-supervisor.git ../ansible-supervisor
  - touch initialized

script:
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'PASS' && exit 0) || (echo 'FAIL' && exit 1)
