---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - git clone https://github.com/futurice/ansible-pip.git ../ansible-pip
  - git clone https://github.com/futurice/ansible-supervisor.git ../ansible-supervisor

script:
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
