---
- pip: name=virtualenv state=latest
- pip: name=celery state=latest virtualenv="{{release_venv}}"
- pip: name=redis state=latest virtualenv="{{release_venv}}"

- template: src=supervisor.conf dest={{supervisor_conf_dir}}celery_supervisor_{{celery_app}}.conf
  when: celery_app
  notify: reload and restart supervisor for project
