---
- pip: name=virtualenv state=latest
- pip: name=celery state=latest virtualenv="{{ virtualenv_path }}"
- pip: name=redis state=latest virtualenv="{{ virtualenv_path }}"
- template: src=supervisor.conf dest={{supervisor_conf_dir}}celery_supervisor_{{app_name}}.conf
  notify: reload and restart supervisor for project
